#define HOST "0.0.0.0"
#define PORT 8080
#define MAX_SIZE 4096
#define NAME_LEN 64
#define DEFAULT_FILE "index.html"
#define CGISTR "cgi-bin/"
#define LOCALDIR "/"
#define DIR "www/"
#define MIN_SIZE 16